name: docker-ci-pipeline
on:
  push:
    paths-ignore:
        -  'LICENSE'
        -  'Dockerfile'
        -  'CONTRIBUTING.md'
        -  'README.md'
        -  'docker-ci.yaml'
jobs:
  dockerci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        
      - name: Build image
        run: docker build -t ${{vars.DOCKER_USERNAME }}/helloworld-demo-python:vj .
        
      - name: Verify the image 
        run: docker images

      - name: Create the container 
        run: docker run --name pythonapp -idt -p 8080:8080 ${{vars.DOCKER_USERNAME }}/helloworld-demo-python:vj

      - name: waiting time 
        run: sleep 20
        
      - name: View the container 
        run: docker ps
        
      - name: curl the container
        run: curl -f http://localhost:8080
        
      - name: Docker login 
        uses: docker/login-action@v3.6.0
        with:
          username: ${{vars.DOCKER_USERNAME }}
          password: ${{secrets.DOCKER_TOKEN }}

      - name: Push the image
        run: docker push ${{vars.DOCKER_USERNAME }}/helloworld-demo-python:vj

      - name: Clean the conatiner
        run: docker rm -f pythonapp

  k8scd-job:
    needs: [dockerci-job]
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        
      - name: start minikube
        uses: medyagh/setup-minikube@latest

      - name: test minikube
        run:  kubectl get pods -A

      - name: apply minikube
        run:  |
          kubectl apply -f k8s/.
          kubectl wait --for=condition=ready pod -l app=python-app
 
      - name: get deplyoment status
        run:  |
          kubectl get ns
          kubectl get deploy,service

      - name: test your application
        run:  |
          minikube service list
          minikube service my-service1 --url
          echo -n "------------------opening the service------------------"
          curl $(minikube service my-service1 --url)
